### PR TITLE
add KindleManga

### PR DESCRIPTION
**Pull request by tung491**

### CODE REVIEW

**Comment by hvnsweeting** [comment]
please run 
```
git fetch --all 
git rebase -i origin/master
git push origin/master -f 
```

**Comment by tung491** [comment]
what do those mean :joy: ?

**Comment by tung491** [comment]
It's ok ?
```
➜  awesome git:(master) git rebase -i origin/master                          
Use "fg" to return to nano.
[1]  + 19969 suspended (signal)  git rebase -i origin/master
➜  awesome git:(master) git push origin master 
Everything up-to-date
➜  awesome git:(master) fq
zsh: command not found: fq
➜  awesome git:(master) 
➜  awesome git:(master) fg
[1]  + 19969 continued  git rebase -i origin/master
Successfully rebased and updated refs/heads/master.
➜  awesome git:(master) git push origin master
Everything up-to-date

```

**Comment by hvnsweeting** [comment]
need fetch all first

**Comment by tung491** [comment]
yes, i dit it, but nothing change
```
➜  awesome git:(master) git fetch --all 
Fetching origin
➜  awesome git:(master) git rebase -i origin/master 
Successfully rebased and updated refs/heads/master.
➜  awesome git:(master) git push origin master
Everything up-to-date
```

**Comment by hvnsweeting** [comment]
Merged, thanks

**Pull request merged**
